version: '3.8'

services:
  web:
    build: ./
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=damir
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=bankaccounting

volumes:
  postgres_volume: