# Generated by Django 4.2.7 on 2023-11-04 17:42

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('image', models.FileField(blank=True, null=True, upload_to='executive_image/', verbose_name='Изображение')),
                ('IIN', models.PositiveBigIntegerField(unique=True)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=main.models.slugify_function, unique=True)),
            ],
            options={
                'verbose_name': 'Руководящее Лицо',
                'verbose_name_plural': 'Руководящие Лица',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveOnOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.executive', verbose_name='Руководящее лицо')),
            ],
            options={
                'verbose_name': 'Руководящее лицо в организаций',
                'verbose_name_plural': 'Руковдящие лица в организацияз',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='FinancialOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип')),
                ('bin', models.CharField(max_length=12, verbose_name='БИН')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('fax', models.CharField(max_length=20, verbose_name='Факс')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('website', models.URLField(max_length=100, verbose_name='Web-сайт')),
                ('second_level_bank', models.CharField(max_length=255, verbose_name='Банк второго уровня')),
                ('insurance_holdings', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страховые холдинги')),
                ('custodian', models.CharField(max_length=255, verbose_name='Кастодиан')),
                ('brokers_dealers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Брокеры-дилеры')),
                ('conglomerates', models.CharField(blank=True, max_length=255, null=True, verbose_name='Банковские конгломераты')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=main.models.slugify_function, unique=True)),
                ('bank_holdings', models.ManyToManyField(blank=True, null=True, to='main.financialorganization', verbose_name='Связанные компаний')),
                ('executives', models.ManyToManyField(related_name='organizations', through='main.ExecutiveOnOrganization', to='main.executive', verbose_name='Руководящие лица')),
                ('participants', models.ManyToManyField(blank=True, null=True, related_name='major_participants', to='main.executive')),
            ],
            options={
                'verbose_name': 'Финансовая Организация',
                'verbose_name_plural': 'Финансовые Организации',
            },
        ),
        migrations.AddField(
            model_name='executiveonorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.financialorganization', verbose_name='Финансовая организация'),
        ),
        migrations.AddField(
            model_name='executive',
            name='position',
            field=models.ManyToManyField(to='main.position', verbose_name='Должность'),
        ),
    ]
