# Generated by Django 4.2.7 on 2023-11-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveonorganization',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.executive', unique=True, verbose_name='Руководящее лицо'),
        ),
        migrations.AlterField(
            model_name='executiveonorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.financialorganization', unique=True, verbose_name='Финансовая организация'),
        ),
    ]
